### ISSUE TITLE
Please share java code to implement this gateway

### ISSUE THREAD

**Issue by primeprogrammer** [eshantmittal/open-payment-android-aar#1]
Sir

I am facing method call expected issue while implemented in java activity

var openPayment: OpenPayment =
    OpenPayment.Builder()
        .with(this@MainActivity)
        .setPaymentToken(body?.id!!) // Add your payment token here
        .setEnvironment(OpenPayment.Environment.SANDBOX)
        .setAccessKey(accessKey) // Add your Access Key here
        .build()

**Comment by eshantmittal** [comment]
Please refer this link for java implementation https://github.com/bankopen/layer-android-sdk-sample-application-java
