### ISSUE TITLE
Cannot access 

### ISSUE THREAD

**Issue by primeprogrammer** [eshantmittal/open-payment-android-aar#2]
Sir error shpws cannot access com.open.open_web_sdk.OpenPayment.Builder

what is the issue in this code.

`    private void setPaymentView(String paymentToken, String accessKey) {
        
        OpenPayment openPayment = new OpenPayment.Builder()
                 .with(this)
                .setPaymentToken(paymentToken)
                .setAccessKey(accessKey)
                .setEnvironment(OpenPayment.Environment.SANDBOX)
                .build();

        openPayment.setPaymentStatusListener(this);

        openPayment.startPayment();
    }
`

**Comment by eshantmittal** [comment]
Share your email id we will connect through mail and rectify the issue.

**Comment by primeprogrammer** [comment]
mahendra@primeprogrammer.com




Prime Programmer




8795202855







On Mon, Jul 13, 2020 at 4:41 PM +0530, "Eshant Mittal" <notifications@github.com> wrote:















Share your email id we will connect through mail and rectify the issue.
