### ISSUE TITLE
Blank window on android 4.4 and 5.1

### ISSUE THREAD

**Issue by android-rk** [eshantmittal/open-payment-android-aar#3]
I just got that when i'm trying to start payment from my 4.4 device and 5.1 device , this show me a blank screen, and on back press shows alert for cancel payment, on tap of yes nothing happens. it stuck.

I'm using this sdk for payment and users making complaints.

**Comment by eshantmittal** [comment]
Hi Ravi,

Please Share your contact details, our team will reach you for more details

**Comment by android-rk** [comment]
email:- ravi.yadav@dil.in
contact :- 8385071301

**Comment by android-rk** [comment]
Any update developers ? cause minimum supported SDK of my app is 19 , so users for 4.4 and 5.1 are stuck. and complains are increasing day by day. So any help will be appreciated.
Attaching screenshots and logs.
[logs.txt](https://github.com/eshantmittal/open-payment-android-aar/files/5236667/logs.txt)

![payment_error](https://user-images.githubusercontent.com/11439722/93426052-e82b5600-f8d8-11ea-84b4-b1efa75087f1.png)
![payment_error01](https://user-images.githubusercontent.com/11439722/93426061-eb264680-f8d8-11ea-9815-63b6ceb58df2.png)

**Comment by eshantmittal** [comment]
Hi Ravi

We are working on that, we will update you soon.

Thanks

**Comment by android-rk** [comment]
Hi there,

I got a crash in firebase console, regarding your SDK please look into this, 


OpenWebViewActivity.java line 1
com.open.open_web_sdk.ui.OpenWebViewActivity$c.onClick

Crash insight
java.lang.IllegalArgumentException; View not attached to window manager
This is a crash caused by your app dismissing a dialog attached to an Activity which is finishing or finished. This can happen in a number of ways -- for example, if an AsyncTask is running while a ProgressDialog is showing, and the user rotates the device, causing the Activity to be recreated.
External resources
View not attached to window manager crash

Fatal Exception: java.lang.IllegalArgumentException
View=DecorView@1f0f64a[OpenWebViewActivity] not attached to window manager
android.view.WindowManagerGlobal.findViewLocked (WindowManagerGlobal.java:533)
android.view.WindowManagerGlobal.removeView (WindowManagerGlobal.java:433)
android.view.WindowManagerImpl.removeViewImmediate (WindowManagerImpl.java:124)
android.app.Dialog.dismissDialog (Dialog.java:518)
android.app.Dialog.dismiss (Dialog.java:501)
androidx.appcompat.app.AppCompatDialog.dismiss (AppCompatDialog.java:140)
android.app.Dialog.cancel (Dialog.java:1462)
com.open.open_web_sdk.ui.OpenWebViewActivity$c.onClick (OpenWebViewActivity.java:1)
androidx.appcompat.app.AlertController$ButtonHandler.handleMessage (AlertController.java:167)
android.os.Handler.dispatchMessage (Handler.java:106)
android.os.Looper.loop (Looper.java:214)
android.app.ActivityThread.main (ActivityThread.java:7081)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:494)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:965)


Device
Brand: samsung
Model: Galaxy J6
Orientation: Portrait
RAM free: 1.85 GB
Disk free: 1.7 GB
Operating System
Version: 9
Orientation: Portrait
Rooted: No

**Comment by eshantmittal** [comment]
> View not attached to window manager

Hi Ravi

This one is resolved we will provide you updated SDK soon. Our team is working on kitkat issue.

Thanks

**Comment by eshantmittal** [comment]
Hi Ravi
 
4.4 device and 5.1 device issue resolved please confirm same. for Orientation issue please update SDK.

**Comment by android-rk** [comment]
Yes it's working now, thank for your kind support.
